In [2]:
import pandas as pd
attention_df=pd.read_csv(r'C:\Users\MCBB\Documents\GitHub\MCI_Python_28S_Level_1\Assignments\Session_04\sample_data.csv', nrows=10)
attention_df

,account_id,ad_id,event_name,timestamp,platform,category_name,region_name,condition_ad_name,price
0,249683985899310273,-159265360436186278,order,2018-05-16 17:33:18.350333,on_behalf,Cars,Đông Bắc Bộ,Mới,267000000
1,2753457128963724056,-6487219347028929285,order,2018-05-04 16:03:08.099983,on_behalf,Cars,Đông Bắc Bộ,Mới,399000000
2,2753457128963724056,-6487219347028929285,order,2018-05-03 15:13:42.447070,on_behalf,Cars,Đông Bắc Bộ,Mới,399000000
3,-4397739266189556976,4054922453976773054,order,2018-05-23 11:15:25.932663,on_behalf,Cars,Hà Nội,Mới,705000000
4,-8143274583979068266,3202538754056800998,order,2018-05-15 17:53:01.634923,on_behalf,Cars,Hà Nội,Mới,696000000
5,6007291878672279226,-1011458500454390912,order,2018-05-03 14:39:53.379256,on_behalf,Cars,Hà Nội,Mới,997000000
6,-8143274583979068266,-5031538607861377271,order,2018-05-02 15:54:24.157315,on_behalf,Cars,Hà Nội,Mới,259000000
7,-7148704049057146074,6927742991209753088,order,2018-05-18 13:05:14.606765,on_behalf,Cars,Hà Nội,Đã sử dụng,538000000
8,8244235460354322809,-1480006483287006729,order,2018-05-04 15:24:31.711427,on_behalf,Cars,Hà Nội,Đã sử dụng,524000000
9,7889304239213447135,-8826716990602725372,order,2018-05-15 17:46:24.973838,on_behalf,Cars,Hà Nội,Đã sử dụng,522000000

In [3]:
attention_df.loc[0]

account_id                   249683985899310273
ad_id                       -159265360436186278
event_name                                order
timestamp            2018-05-16 17:33:18.350333
platform                              on_behalf
category_name                              Cars
region_name                         Đông Bắc Bộ
condition_ad_name                           Mới
price                                 267000000
Name: 0, dtype: object